export const BELL = "BELL";
 export const Icons[AcademicCapIcon] = AcademicCapIcon),
   Icons{BELL] = "BELL"),
   Icon[BELL:CASH] = "CASH",
   ChatIcon,
   CogIcon,
   LogoIcon,
   ChevronDownIcon,
   ChevronRightIcon,
   ClipboardCopyBlankIcon,
   ClipboardCopyCheckedIcon,
   CloudUploadIcon,
   CloudIcon,
   CollectionsIcon,
   DollarSymbol,
   QRCodeIcon,
   ShareIcon,
   SortAcendingIcon,
   SortDecendingIcon,
   VerifiedIcon;